adding workflow for one touch deployment

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,47 +1,39 @@
-name: Deploy to Kamal
-
+name: Kamal Deployment
 on:
   push:
     branches:
-      - main
+      - main 
 
 jobs:
-  build_and_deploy:
+  deploy:
     runs-on: ubuntu-latest
-
     steps:
-    - name: Checkout code
+    - name: Checkout repository
       uses: actions/checkout@v3
 
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v2
-
-    - name: Log in to Docker Hub
-      uses: docker/login-action@v2
+    - name: Install Ruby and Gems
+      uses: ruby/setup-ruby@v3
       with:
-        username: ${{ secrets.DOCKER_USERNAME }}
-        password: ${{ secrets.DOCKER_PASSWORD }}
+        bundler-cache: true
 
-    - name: Build and push Docker image
-      run: |
-        IMAGE_TAG=${{ github.sha }}   # Tagging the image with the commit SHA
-        docker buildx build --platform linux/amd64 \
-          --tag pratikingle09/kamal_project_rails:$IMAGE_TAG \
-          --tag pratikingle09/kamal_project_rails:latest \
-          --push .   # The `--push` flag ensures the image is pushed to Docker Hub
-          
     - name: Install Kamal
-      run: |
-        gem install --user-install kamal
-        echo "::add-path::$HOME/.gem/ruby/3.0.0/bin"   # Ensure Kamal is in the PATH
+      run: gem install kamal
 
-    - name: Deploy to Kamal
+    - name: Set up SSH
       run: |
-        kamal deploy \
-          --image pratikingle09/kamal_project_rails:${{ github.sha }}
-      continue-on-error: false
+        mkdir -p ~/.ssh
+        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
+        echo "RAILS_MASTER_KEY=$RAILS_MASTER_KEY" >> .env
+        echo "KAMAL_REGISTRY_PASSWORD=$KAMAL_REGISTRY_PASSWORD" >> .env
+        chmod 600 ~/.ssh/id_rsa
+        ssh-keyscan 15.206.125.202 >> ~/.ssh/known_hosts || echo "Failed to add host"
+        ssh-keyscan 3.110.49.102 >> ~/.ssh/known_hosts || echo "Failed to add host"
 
-    - name: Rollback if deployment fails
-      if: ${{ failure() }}
-      run: |
-        kamal rollback
+      env:
+        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
+        KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
+        SECRET_KEY_BASE: ${{secrets.SECRET_KEY_BASE}}
+
+    - name: Kamal Deploy
+      run: kamal deploy
